### ISSUE TITLE
Unmaintained? Archive it?

### ISSUE THREAD

**Issue by Trott** [pkgjs/create-package-json#185]
Nothing has landed in 10 months, there are critical and high dependency vulnerabilities unaddressed, and the package.json indicates that it only supports up to Node.js 16.x. Archive this repo?

@pkgjs/node-tsc

**Comment by ljharb** [comment]
I'm not sure why there's a rush to archive it. Just because it's a stalled initiative doesn't mean there's any harm in letting it sit.

**Comment by ljharb** [comment]
Either way it seems like something the Package Management group should be deciding on before involving the node TSC?

**Comment by Trott** [comment]
> I'm not sure why there's a rush to archive it.

There's no "rush to archive it".

That said, there's no reason to be hesitant or overly-cautious about archiving it either. Unarchiving is trivial. If archiving the repository sends the correct message about the software's current maintenance status (which--maybe it does and maybe it doesn't), then that probably is the most important thing.

**Comment by wesleytodd** [comment]
Hey! I have been looking for recruits for years on this. I had two folks hooked in who just didn't have time and I have always meant to get back to it, but now with the . The goal here is to encapsulate all the work from the https://github.com/openjs-foundation/package-json-research group picking up this will become a priority again. I am going to close this issue, and will be pushing at least some updates and automation to keep it more fresh today.
