### ISSUE TITLE
Moved but not meeting org criteria

### ISSUE THREAD

**Issue by wesleytodd** [pkgjs/create-package-json#75]
Hey folks, sorry for the delays on this.  Lots going on and I had hoped to find the time to update things like the license and CoC before moving.  Since I have not had time I figured I would finally just move it and let folks with the time do that.  FWIW, I had added anyone who needed it even while I owned it, but this is a better home.  Just wanted to drop this issue here to track getting those requirements updated.

**Comment by wesleytodd** [comment]
@mhdawson do you happen to know if the stuff in https://github.com/pkgjs/.github is enough of if I need to change anything in this repo to be in line with the other projects the PMWG owns?

**Comment by mhdawson** [comment]
@wesleytodd in addition to what I see in  https://github.com/pkgjs/.github it needs a licence which I see already exists in the repo

**Comment by wesleytodd** [comment]
Ok, I will close this then. Just wanted to make sure it was meeting our standards. Thanks!
